name: 01 Hello Workflow

on:
  pull_request:
    type: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  if: github.event.pull_request.merged == true
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Hello from GitHub Actions Hello from mohamed"